<style>
    .margin5{
        line-height: 41px;
    }
    .layui-btn-sm-category{
        margin-right: 12px;
        margin-left: 0!important;
    }
</style>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">

                <div class="layui-form-item">
                    <div>
                        <input type="hidden" name="categories" id="category" value="">
                        <div class="layui-row">
                            <label class="layui-form-label">板块:</label>
                            <div class="layui-col-md11 margin5">
                                <button lay-active="category" data-id="" type="button" class="layui-btn layui-margin-top layui-btn-sm-category layui-btn-sm">全部</button>
                                <?php foreach ($categoryItems as $key=>$val):?>
                                    <button lay-active="category" data-id="<?php echo $val['id'];?>" type="button" class="layui-btn layui-margin-top layui-btn-sm-category layui-category layui-btn-primary layui-btn-sm"><?php echo $val['id']." | ".$val['name']; ?></button>
                                <?php endforeach;?>
                            </div>
                        </div>
                    </div>
                    <hr class="layui-border-black">
                </div>
                <div class="layui-form-item">
                    <div class="layui-row">
                        <div class="layui-inline">
                            <label class="layui-form-label">状态:</label>
                            <div class="layui-input-inline">
                                <select name="status">
                                    <option value="">请选择..</option>
                                    <?php foreach ($statusArr as $key=>$item): ?>
                                        <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">购买类型:</label>
                            <div class="layui-input-inline">
                                <select name="pay_type">
                                    <option value="">请选择..</option>
                                    <?php foreach ($payTypeArr as $key=>$item): ?>
                                        <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">置顶:</label>
                            <div class="layui-input-inline">
                                <select name="is_top">
                                    <option value="">请选择..</option>
                                    <?php foreach ($topArr as $key=>$item): ?>
                                        <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">热门:</label>
                            <div class="layui-input-inline">
                                <select name="is_hot">
                                    <option value="">请选择..</option>
                                    <?php foreach ($hotArr as $key=>$item): ?>
                                        <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <hr class="layui-border-black">
                </div>

                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">标题:</label>
                        <div class="layui-input-inline">
                            <input name="title" class="layui-input" placeholder="输入标题"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">帖子ID:</label>
                        <div class="layui-input-inline">
                            <input name="id" class="layui-input" placeholder="输入帖子ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID:</label>
                        <div class="layui-input-inline">
                            <input name="user_id" class="layui-input" placeholder="输入用户ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">开始时间:</label>
                        <div class="layui-input-inline">
                            <input type="text" class="layui-input" name="start_time"  readonly="" id="start_time" placeholder="yyyy-MM-dd HH:mm:ss">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">结束时间:</label>
                        <div class="layui-input-inline">
                            <input type="text" class="layui-input" name="end_time"  readonly="" id="end_time" placeholder="yyyy-MM-dd HH:mm:ss">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
                    <button class="layui-btn layui-btn-xs" lay-event="add">添加</button>
                    <button class="layui-btn layui-btn-xs" lay-event="asyncFromMrs">同步资源库</button>
                    <button class="layui-btn layui-btn-xs" lay-event="changeFromMovie">视频转帖子</button>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>
                    <button class="layui-btn layui-btn-xs " lay-event="update">批量设置</button>
                    <button class="layui-btn layui-btn-xs layui-btn-primary" lay-event="es">刷新索引</button>
                    <button class="layui-btn layui-btn-xs layui-btn-warm" lay-event="adminLogs">运营工作签到</button>
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
                <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
                <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="comment">评论</a>
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,util,laydate,$;
    layui.use(['layer', 'form', 'table', 'admin', 'util', 'laydate'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        util = layui.util;
        laydate = layui.laydate;
        table = layui.table;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:30
                ,limits:[10,30,50,100]
            }
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {title:'操作', toolbar: '#table-item-toolbar',align: 'center', width:150}
                ,{type: 'checkbox'}
                ,{field:'_id', title: 'ID',align: 'center', width: 120}
                ,{field: 'user_info', title:'用户信息', templet: function (row) {
                        var str='';
                        if(row.is_system==1){
                            str= "<p style='color: red'>"+row.user_id+"</p>"+"<p style='color: red'>"+row.nickname+"("+row.user_sex+")</p>"
                        }else {
                            str="<p >"+row.user_id+"</p>"+"<p>"+row.nickname+"("+row.user_sex+")</p>";
                        }
                        str+="<p>用户组:"+row.group_name+"</p>";
                        return str;
                    },width:150,align: 'center'}
                ,{field: 'head', title:'用户头像', width: 60, templet: function (row) {
                    if(row.head){
                        var link='<?php echo $mediaUrl;?>'+row.head;
                        return '<a target="_blank" href="'+link+'" ><img src="'+link+'" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="max-width: 50px;max-height: 50px"/></a>'
                    }
                    return '-';
                },align: 'center'}
                ,{field:'title', title: '标题',align: 'center',width:220}
                ,{field: 'images', title:'封面',align: 'left', templet: function (row) {
                   var postImgs = '';
                    $.each(row.images,function (i,e) {
                        if(i<2){
                            e = '<?php echo $mediaUrl;?>'+e;
                            postImgs += '<a target="_blank" href="'+e+'" ><img src="'+e+'" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="width: 33px;height: 33px;margin-left:6px;margin-top:6px;"/></a>';
                        }
                    });
                    return postImgs?postImgs:'-';
                }, width: 100}
                ,{field: 'categories', title: '分类',align: 'center',width: 100}
                ,{field: 'type_text', title: '类型',align: 'center',width: 80}
                ,{field: 'status', title: '状态',align: 'center',width: 50}
                ,{field: 'position', title: '分区',align: 'center',width: 70}
                ,{field: 'is_top', title: '置顶',align: 'center',width: 70}
                ,{field: 'is_hot', title: '热门',align: 'center',width: 70}
                ,{field: 'real_click', title: '点击',align: 'center',width: 70}
                ,{field: 'real_love', title: '赞',align: 'center',width: 60}
                ,{field: 'real_favorite', title: '收藏',align: 'center',width: 60}
                ,{field: 'comment', title: '评论',align: 'center',width: 60}
                ,{field: 'pay_type', title: '购买类型',align: 'center',width: 80}
                ,{field: 'sort', title: '排序',align: 'center',width: 50}
                ,{field: 'created_at', title: '创建时间',align: 'center',width: 80}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function(obj){
            var order=obj.type==='asc'?1:-1;
            table.reload('table', {initSort: obj,where: {sort: obj.field,order: order }});
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function(obj){
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for(var index=0;index<data.length;index++)
            {
                ids.push(data[index]._id)
            }
            switch(obj.event) {
                case 'add':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/post/detail'); ?>",
                        area:  ['90%', '80%']
                    });
                    break;
                case 'del':
                    doRow(ids,'del');
                    break;
                case 'update':
                    updateRow(ids);
                    break;
                case 'es':
                    doRow(ids,'es');
                    break;
                case 'changeFromMovie':
                    changeFromMovie();
                    break;
                case 'asyncFromMrs':
                    asyncFromMrs();
                    break;
                case 'adminLogs':
                    adminLogs();
                    break;
            }
        });

        //监听其他事件
        util.event('lay-active', {
            category: function(e){
                $('.layui-btn-sm-category').addClass('layui-btn-primary');
                e.removeClass('layui-btn-primary');
                $("#category").val(e.attr('data-id'));
            }
        });

        //时间
        laydate.render({
            elem: '#end_time',
            type: 'datetime'
        });
        laydate.render({
            elem: '#start_time',
            type: 'datetime'
        });

        /*表格-行事件*/
        table.on('tool(table)', function(obj){
            var data = obj.data;
            switch (obj.event) {
                case 'edit':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/post/detail'); ?>?_id="+data._id,
                        area:  ['90%', '80%']
                    });
                    break;
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids,'del');
                    break;
                case 'comment':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/comment/post'); ?>?object_id="+data._id,
                        area:  ['90%', '80%']
                    });
                    break;
            }
        });

        //视频转帖子
        function changeFromMovie() {
            layer.prompt({
                formType: 2,
                value: '',
                title: '请输入媒资库视频ID',
                area: ['500px', '300px']
            }, function(value, index, elem){
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/post/changeFromMovie')?>",{id:value},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        layer.close(index);
                        layerIndex=layer.open({
                            type: 2,
                            content: "<?php echo createUrl('/post/detail'); ?>?mid="+value,
                            area:  ['90%', '80%']
                        });
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }

        //同步帖子
        function asyncFromMrs() {
            layer.prompt({
                formType: 2,
                value: '',
                title: '请输入媒资库帖子ID',
                area: ['500px', '300px']
            }, function(value, index, elem){
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/post/asyncFromMrs')?>",{id:value},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        layer.close(index);
                        table.reload('table');
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }

        function doRow(ids,act) {
            if(ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?",function() {
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/post/do')?>",{act:act,id:ids.join(",")},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }

        //签到
        function adminLogs() {
            showConfirmMsg("确定操作吗?",function() {
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/system/adminLogs')?>",{},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        showSuccessMsg("签到成功!");
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }

        //批量设置
        function updateRow(ids) {
            ids=ids.join(',');
            if( ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            layerIndex=layer.open({
                type: 2,
                shade: 0.8,
                content: "<?php echo createUrl('/post/update'); ?>?ids="+ids,
                area: ['1000px', '80%'],
            });
        }
    })
</script>
