<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">批量设置</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">ID:</label>
                            <div class="layui-input-block">
                                <input type="text" readonly name="id" value="<?php echo $ids;?>"  placeholder="" autocomplete="off" class="layui-input layui-disabled">
                            </div>
                        </div>

                        <div class="layui-form-item" pane="">
                            <label class="layui-form-label">板块:</label>
                            <div class="layui-input-block">
                                <?php foreach ($categoryItems as $key=>$val):?>
                                    <input type="checkbox" name="categories[]" <?php if($row['categories']&&in_array($val['id'],$row['categories'])):?>checked<?php endif;?> value="<?php echo $val['id'];?>" lay-skin="primary" title="<?php echo $val['name'];?>">
                                <?php endforeach;?>
                            </div>
                            <div class="layui-input-block">
                                帖子分区 暗圈和社区 是跟随第一个板块所属分区
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">热门:</label>
                            <div class="layui-input-block">
                                <input type="radio" name="is_hot" value="" checked title="请选择">
                                <?php foreach ($hotArr as $key=>$item): ?>
                                    <input type="radio" name="is_hot" value="<?php echo $key; ?>" title="<?php echo $item; ?>">
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">置顶:</label>
                            <div class="layui-input-block">
                                <input type="radio" name="is_top" value="" checked title="请选择">
                                <?php foreach ($hotArr as $key=>$item): ?>
                                    <input type="radio" name="is_top" value="<?php echo $key; ?>" title="<?php echo $item; ?>">
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">状态:</label>
                            <div class="layui-input-block">
                                <input type="radio" name="status" value="" checked title="请选择">
                                <?php foreach ($statusArr as $key=>$item): ?>
                                    <input type="radio" name="status" value="<?php echo $key; ?>" title="<?php echo $item; ?>" >
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">用户ID:</label>
                            <div class="layui-input-block">
                                <input name="user_id" placeholder="请输入用户ID" class="layui-input" autocomplete="off" type="number" lay-verType="tips"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">金币:</label>
                            <div class="layui-input-block">
                                <input type="text" name="money" value=""  placeholder="" autocomplete="off" class="layui-input">
                                <div class="layui-form-mid layui-word-aux">金币>0 vip=0 免费<0 主要用于附件</div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">上架时间</label>
                            <div class="layui-input-block">
                                <input type="text" name="created_at" id="created_at" placeholder="" autocomplete="off" class="layui-input  icon-date">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form','upload','laydate'], function(){
        var $ = layui.$,element = layui.element,form = layui.form,upload = layui.upload,laydate = layui.laydate;
        //日期时间选择器
        laydate.render({
            elem: '#created_at'
            ,type: 'datetime'
        });
        form.render(null, 'info-form');
        element.render('breadcrumb', 'breadcrumb');

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            obj.field.act='update';
            doAjax("<?php echo createUrl('/post/do')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
