<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">域名详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id"  placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">链接</label>
                            <div class="layui-input-block">
                                <input type="text" name="url" lay-verify="required" placeholder="" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">类型</label>
                            <div class="layui-input-block">
                                <select name="type"  class="layui-input">
                                    <option value="">请选择..</option>
                                    <?php foreach ($typeArr as $value=>$label):?>
                                        <option value="<?php echo $value;?>"><?php echo $label;?></option>
                                    <?php endforeach;?>
                                </select>
                                <div class="layui-word-aux">
                                    'h5_proxy' => 'H5代理'=>'H5跳转前的域名也是ios描述文件里面的域名,跳转到h线路'<br>
                                    'h5' => 'H5线路'=>'H5线路 ios真实的域名'<br>
                                    'private' => '保护域名'=>'官方域名'<br>
                                    'web' => '落地页域名'=>'落地页域名,主要是官方域名分享域名等使用'<br>
                                    'channel' => '渠道域名'=>'渠道域名是对外投放的域名,一定要及时更新'<br>
                                    'public_channel_web' => '落地页绑定渠道号的域名'=>'落地页绑定渠道号的域名，一般渠道投放需要用到'<br>
                                    'public_channel_h5' => 'H5绑定渠道号的域名'=>'H5绑定渠道号的域名，一般渠道投放需要用到'<br>
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">状态:</label>
                            <div class="layui-input-block">
                                <select name="status"  class="layui-input">
                                    <?php foreach ($statusArr as $value=>$label):?>
                                        <option value="<?php echo $value;?>"><?php echo $label;?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">渠道</label>
                            <div class="layui-input-block">
                                <input name="channel_code" placeholder="请输入绑定渠道" autocomplete="off" value="" type="text" class="layui-input" />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">统计代码</label>
                            <div class="layui-input-block">
                                <textarea name="count_code" rows="3"  maxlength="2000" placeholder="请输入"  class="layui-textarea"></textarea>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label ">备注</label>
                            <div class="layui-input-block">
                                <input type="text" name="remark" placeholder="" autocomplete="off" class="layui-input">
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form'], function(){
        var $ = layui.$
            ,element = layui.element
            ,form = layui.form;
        form.val('info-form',<?php echo json_encode($row);?>);
        form.render(null, 'info-form');

        element.render('breadcrumb', 'breadcrumb');

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/domain/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
