<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID:</label>
                        <div class="layui-input-inline">
                            <input name="_id" class="layui-input" placeholder="用户ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">用户名:</label>
                        <div class="layui-input-inline">
                            <input name="username" class="layui-input" placeholder="用户名"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">渠道名称:</label>
                        <div class="layui-input-inline">
                            <input name="channel_name" class="layui-input" placeholder="渠道名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">设备:</label>
                        <div class="layui-input-inline">
                            <select name="device_type">
                                <option value="" selected>请选择..</option>
                                <?php foreach ($deviceArr as $device => $label): ?>
                                    <option value="<?php echo $device; ?>"><?php echo $label; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">余额位置:</label>
                        <div class="layui-input-inline">
                            <select name="type">
                                <option value="" selected>请选择..</option>
                                <?php foreach ($balanceArr as $key => $val): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">状态:</label>
                        <div class="layui-input-inline">
                            <select name="status">
                                <option value="" selected>请选择..</option>
                                <?php foreach ($statusArr as $key => $val): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>

        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,$;
    layui.use(['layer', 'form', 'table', 'admin'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:30
                ,limits:[10,30,50,100]
            }
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {field: 'user_info', title:'用户信息', templet: function (row) {
                        var str='';
                        if(row.is_system==1){
                            str= "<p style='color: red'>"+row.user_id+"</p>"+"<p style='color: red'>"+row.nickname+"("+row.user_sex+")</p>"
                        }else {
                            str="<p >"+row.user_id+"</p>"+"<p>"+row.nickname+"("+row.user_sex+")</p>";
                        }
                        str+="<p>用户组:"+row.group_name+"</p>";
                        return str;
                    },align: 'center'},
                {field: 'head', title:'用户头像', width: 120, templet: function (row) {
                        if(row.head){
                            var link='<?php echo $mediaUrl;?>'+row.head;
                            return '<a target="_blank" href="'+link+'" ><img src="'+link+'" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="max-width: 50px;max-height: 50px"/></a>'
                        }
                        return '-';
                    },align: 'center'},
                {field: 'username', title: '用户名',width:200,align: 'center'},
                {field: 'channel_name', title: '渠道',width:120,align: 'center'},
                {field: 'device_type', title: '设备',width:120,align: 'center'},
                {field: 'balance', title: '带入金额',width:120,align: 'center', sort:true},
                {field: 'balance_text', title: '余额所在位置',width:120,align: 'center'},
                {field: 'status_text', title: '状态',width:80,align: 'center'},
                {field: 'updated_at', title: '失败时间',width:120,align: 'center', sort:true},
                {field: 'error_msg', title: '错误信息',style:'color:red',width:120,align: 'center'},
                {field: 'created_at', title: '创建时间',width:120,align: 'center', sort:true},
                // {field: 'info', title: '其他信息',width:220,align: 'center'},
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function(obj){
            var order=obj.type==='asc'?1:-1;
            table.reload('table', {initSort: obj,where: {sort: obj.field,order: order }});
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function(obj){
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for(var index=0;index<data.length;index++)
            {
                ids.push(data[index]._id)
            }
            switch(obj.event) {
                case 'award':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/activityUser/detail'); ?>",
                        area:  ['88%', '88%']
                    });
                    break;
            }
        });
    })
</script>
