<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">每日推荐</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <div class="layui-form-item">
                            <label class="layui-form-label">日期</label>
                            <div class="layui-input-block">
                                <input name="label" id="report-date" value="" class="layui-input icon-date" placeholder="请输入日期"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">视频ID</label>
                            <div class="layui-input-block">
                                <textarea name="ids" placeholder="请输入视频ID" class="layui-textarea"></textarea>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form','laydate'], function(){
        var $ = layui.$
            ,element = layui.element
            ,form = layui.form
            ,laydate = layui.laydate;
        form.val('info-form',<?php echo $row;?>);
        form.render(null, 'info-form');

        element.render('breadcrumb', 'breadcrumb');

        laydate.render({
            elem: '#report-date',
            type: 'date'
        });
        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/movieDay/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
