<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">用户任务详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id"  placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">名称:</label>
                            <div class="layui-input-block">
                                <input name="name" placeholder="请输入名称" autocomplete="off" class="layui-input" lay-verType="tips"
                                       lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">类型:</label>
                            <div class="layui-input-block">
                                <select name="type" lay-verType="tips" lay-verify="required" required>
                                    <option value="">请选择..</option>
                                    <?php foreach ($typeArr as $value=>$label):?>
                                        <option value="<?php echo $value;?>"><?php echo $value.' | '.$label;?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">描述:</label>
                            <div class="layui-input-block">
                                <input name="description" placeholder="请输入描述" value="" autocomplete="off" type="text" class="layui-input" lay-verType="tips"
                                       lay-verify="required" required />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">排序:</label>
                            <div class="layui-input-block">
                                <input name="sort" placeholder="请输入排序" value="0" autocomplete="off" type="text" class="layui-input " lay-verType="tips"
                                       lay-verify="required" required />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">每次积分:</label>
                            <div class="layui-input-block">
                                <input name="num" placeholder="请输入每次赠送" value="0" autocomplete="off" type="text" class="layui-input " lay-verType="tips"
                                       lay-verify="required" required />
                                <div class="layui-word-aux">每次赠送的积分 只有下载 登陆 评论有效</div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">链接:</label>
                            <div class="layui-input-block">
                                <input name="link" placeholder="请输入链接" value="" autocomplete="off" type="text" class="layui-input " lay-verType="tips"/>
                                <div class="layui-word-aux">下载任务时候的链接</div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form', 'upload'], function(){
        var $ = layui.$
            ,element = layui.element
            ,upload = layui.upload
            ,form = layui.form
            ,row = <?php echo json_encode($row);?>;

        form.val('info-form', row);
        form.render(null, 'info-form');

        element.render('breadcrumb', 'breadcrumb');

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/userTask/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
