<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">用户等级详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id"  placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">名称:</label>
                            <div class="layui-input-block">
                                <input name="name" placeholder="请输入名称" class="layui-input" lay-verType="tips"
                                       lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">等级:</label>
                            <div class="layui-input-block">
                                <select name="level" lay-verType="tips" lay-verify="required" required>
                                    <option value="">请选择..</option>
                                    <?php foreach ($levelItems as $value=>$label):?>
                                        <option value="<?php echo $value;?>"><?php echo $value.' | '.$label;?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">促销类型:</label>
                            <div class="layui-input-block">
                                <select name="promotion_type" lay-verType="tips" lay-verify="required" required>
                                    <option value="">请选择..</option>
                                    <?php foreach ($typeItems as $value=>$label):?>
                                        <option value="<?php echo $value;?>"><?php echo $label;?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">价格:</label>
                            <div class="layui-input-block">
                                <input name="price" placeholder="请输入价格" value="0" type="text" class="layui-input " lay-verType="tips"
                                       lay-verify="required" required />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">原价:</label>
                            <div class="layui-input-block">
                                <input name="old_price" placeholder="请输入原价" value="0" type="number" class="layui-input" lay-verType="tips"
                                       lay-verify="required" required />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">购片折扣:</label>
                            <div class="layui-input-block">
                                <input name="rate" placeholder="请输入折扣" value="100" type="text" class="layui-input " lay-verType="tips"
                                       lay-verify="required" required />
                                <div class="layui-word-aux">
                                    1.购买金币视频或者金币帖子的折扣,实际上帖子的折扣无效<br>
                                    2.填写-1表示金币视频免费<br>
                                    3.填写-2表示金币视频和金币帖子免费
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">可用天数:</label>
                            <div class="layui-input-block">
                                <input name="day_num" placeholder="请输入可用天数" value="0" type="number" class="layui-input" lay-verType="tips"
                                       lay-verify="required" required />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">赠送金币:</label>
                            <div class="layui-input-block">
                                <input name="gift_num" placeholder="请输入赠送金币" value="0" type="number" class="layui-input" lay-verType="tips"
                                       lay-verify="required" required />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">下载次数:</label>
                            <div class="layui-input-block">
                                <input name="download_num" placeholder="请输入下载次数" value="0" type="number" class="layui-input" lay-verType="tips"
                                       lay-verify="required" required />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">天数提示:</label>
                            <div class="layui-input-block">
                                <input name="day_tips" placeholder="请输入天数提示" value="" type="text" class="layui-input"  />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">价格提示:</label>
                            <div class="layui-input-block">
                                <input name="price_tips" placeholder="请输入价格提示" value="" type="text" class="layui-input"  />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">排序:</label>
                            <div class="layui-input-block">
                                <input name="sort" placeholder="请输入排序" class="layui-input" type="number" value="0" lay-verType="tips"
                                       lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">封面:</label>
                            <div class="layui-input-block">
                                <div id="imgX" class="user-tag upload-select-picture-card">
                                    <span class="layui-icon layui-icon-addition"></span>
                                </div>
                                <input name="img" id="imgXInput"  value="" type="hidden" class="layui-input" />
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">描述:</label>
                            <div class="layui-input-block">
                                <textarea name="description" class="layui-textarea"></textarea>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">是否禁用:</label>
                            <div class="layui-input-block">
                                <input name="is_disabled" type="radio" value="0" title="否" checked/>
                                <input name="is_disabled" type="radio" value="1" title="是"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">会员权益:</label>
                            <div class="layui-input-block">
                                <?php foreach ($userRightsItems as $value=>$text):?>
                                    <input type="checkbox" name="rights[]" <?php if($row['rights']&&in_array($value,$row['rights'])):?>checked<?php endif;?>  value="<?php echo $value;?>" lay-skin="primary" title="<?php echo $value.' | '.$text;?>">
                                <?php endforeach;?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">谷歌验证码:</label>
                            <div class="layui-input-block">
                                <input name="google_code" placeholder="请输入谷歌验证码,5分钟有效" value="" type="text" class="layui-input"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form', 'upload'], function(){
        var $ = layui.$
            ,element = layui.element
            ,upload = layui.upload
            ,form = layui.form
            ,row = <?php echo json_encode($row);?>;

        form.val('info-form', row);
        form.render(null, 'info-form');

        element.render('breadcrumb', 'breadcrumb');

        //回显部分数据是
        if(row && row.img){
            $("#imgX").html("<img width='290' src='<?php echo $mediaUrl;?>"+row.img+"'>");
        }

        //上传图片
        upload.render({
            elem: '#imgX' //绑定元素
            ,url: '<?php echo $uploadUrl; ?>' //上传接口
            ,before: function(obj){
                layer.load(0,{time: 30*1000});
            }
            ,done: function(res){
                layer.closeAll('loading');
                if(res.status=='y') {
                    $("#imgX").html("<img width='290' src='<?php echo $mediaUrl;?>"+res.data+"'>");
                    $("#imgXInput").val(res.data);
                }else {
                    showErrorMsg(res.error)
                }
            }
            ,error: function(){
                //请求异常回调
                showErrorMsg('上传异常')
            }
        });

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/userGroup/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
