<style>
    .layui-margin-top{
        margin-top: 6px;
        margin-bottom: 6px;
    }
</style>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar  search-form" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div>
                        <input type="hidden" name="tags" id="tag" value="">
                        <?php foreach ($tagArr as $group=>$tag):?>
                        <div class="layui-row">
                            <div class="layui-col-md1">
                                <label class="layui-form-label"><?php echo \App\Constants\CommonValues::getMovieTagAttribute($group);?>:</label>
                            </div>
                            <div class="layui-col-md11">
                                <?php foreach ($tag as $item):?>
                                    <button lay-active="tag" data-id="<?php echo $item['id'];?>" type="button" class="layui-btn layui-margin-top layui-btn-sm-tag layui-btn-primary layui-btn-sm"><?php echo $item['id']." | ".$item['name']; ?></button>
                                <?php endforeach;?>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                    <hr class="layui-border-black">
                </div>

                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">视频来源:</label>
                        <div class="layui-input-inline">
                            <select name="source" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($sourceArr as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">画布:</label>
                        <div class="layui-input-inline">
                            <select name="canvas" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($canvasArr as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">封面:</label>
                        <div class="layui-input-inline">
                            <select name="img_type" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($canvasArr as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">分类:</label>
                        <div class="layui-input-inline">
                            <select name="categories" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($catArr as $item): ?>
                                    <option value="<?php echo $item['id']; ?>"><?php echo $item['id'].' | '.$item['name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">购买:</label>
                        <div class="layui-input-inline">
                            <select name="pay_type" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($payTypeArr as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">分区:</label>
                        <div class="layui-input-inline">
                            <select name="position" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($posArr as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">最新:</label>
                        <div class="layui-input-inline">
                            <select name="is_new" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($newArr as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">热门:</label>
                        <div class="layui-input-inline">
                            <select name="is_hot" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($hotArr as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">状态:</label>
                        <div class="layui-input-inline">
                            <select name="status" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($statusArr as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>" <?php if($key==$defaultStatus){ echo  'selected';};?>><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">剧集:</label>
                        <div class="layui-input-inline">
                            <select name="is_more_link" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($linkTypeArr as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">观看范围:</label>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="clickMinSort" placeholder="最小值" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="clickMaxSort" placeholder="最大值" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">收藏率范围:</label>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="favMinSort" placeholder="最小值" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="favMaxSort" placeholder="最大值" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">排序范围:</label>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="minSort" placeholder="最小值" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="maxSort" placeholder="最大值" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID:</label>
                        <div class="layui-input-inline">
                            <input name="user_id" class="layui-input"  autocomplete="off" placeholder=""/>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">ID:</label>
                        <div class="layui-input-inline">
                            <input name="_id" class="layui-input"  autocomplete="off" placeholder="请输入视频ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">媒资ID:</label>
                        <div class="layui-input-inline">
                            <input name="mid" class="layui-input"  autocomplete="off" placeholder="格式 xb_1002"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">名称:</label>
                        <div class="layui-input-inline">
                            <input name="name" class="layui-input"  autocomplete="off" placeholder="请输入名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">番号:</label>
                        <div class="layui-input-inline">
                            <input name="number" class="layui-input"  autocomplete="off" placeholder="请输入番号"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
                    <button class="layui-btn layui-btn-xs" lay-event="up">上架</button>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="down">下架</button>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>
                    <button class="layui-btn layui-btn-xs" lay-event="async">媒资同步</button>
                    <button class="layui-btn layui-btn-xs " lay-event="update">批量设置</button>
                    <button class="layui-btn layui-btn-xs  layui-btn-danger" lay-event="clearTag">清空标签</button>
                    <button class="layui-btn layui-btn-xs layui-btn-primary" lay-event="es">刷新索引</button>
                    <button class="layui-btn layui-btn-xs layui-btn-warm" lay-event="adminLogs">运营工作签到</button>
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
                <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,util,$;
    layui.use(['layer', 'form', 'table', 'admin','util'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        util = layui.util;
        table = layui.table;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:30
                ,limits:[10,30,50,100]
            }
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {title:'操作',align: 'center', width:150,templet:function (row) {
                        var html = '<a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>';
                        if(row.is_more_link===1){
                            html += '<a class="layui-btn layui-btn-xs" lay-event="more_link">剧集</a>';
                        }
                        html +='<a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="comment">评论</a>';
                        return html;
                    }}
                ,{type: 'checkbox'}
                ,{field:'_id', title: 'ID',width:180,align: 'center'}
                ,{field:'name', title: '名称', templet: function (row) {
                        return row.name;
                }, align: 'center'}
                ,{field: 'img_x', title:'封面',width:100, templet: function (row) {
                    if(row.img_x){
                        var link = '<?php echo $mediaUrl;?>' + row.img_x;
                        return '<a target="_blank" href="'+link+'" ><img src="'+link+'" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="max-width: 60px;max-height: 35px"/></a>'
                    }
                    return '-';
                }, align: 'center'}
                ,{field:'categories', title: '分类',width:60,align: 'center'}
                ,{field:'tags', title: '标签', align: 'center'}
                ,{field:'duration', title: '时长',width:80,align: 'center',sort:true,style:'color:#01AAED'}
                ,{field:'pay_type', title: '购买类型',width:80,align: 'center',style:'color:red',templet:function (row) {
                    if(row.pay_type=='money'){
                        return row.pay_type+" ￥:"+row.money;
                    }
                    return row.pay_type;
                }}
                ,{field:'user_id', title: '用户编号',width:80,align: 'center'}
                ,{field:'real_click', title: '点击',width:50,align: 'center',sort:true}
                ,{field:'comment', title: '评论',width:50,align: 'center',sort:true}
                ,{field:'real_favorite', title: '收藏',width:50,align: 'center',sort:true}
                ,{field:'favorite_rate', title: '收藏率',width:60,align: 'center',sort:true}
                ,{field:'buy', title: '销售次数',width:70,align: 'center',sort:true}
                ,{field:'sort', title: '排序',width:70,align: 'center',sort:true}
                ,{field:'is_new', title: '最新',width:50,align: 'center'}
                ,{field:'is_hot', title: '热门',width:50,align: 'center'}
                ,{field:'status', title: '状态',width:50,align: 'center'}
                ,{field:'position', title: '分区',width:50,align: 'center'}
                ,{field:'is_more_link_text', title: '剧集',width:50,align: 'center'}
                ,{field:'img_type', title: '封面',width:60,align: 'center',style:'color:#01AAED'}
                ,{field:'canvas', title: '画布',width:60,align: 'center',style:'color:#01AAED'}
                ,{field:'show_at', title: '上架时间',width:100,align: 'center',sort:true}
                ,{field:'created_at', title: '创建时间',align: 'center',width:100,sort:true}
                //,{title:'操作', toolbar: '#table-item-toolbar',align: 'center', width:150}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function(obj){
            var order=obj.type==='asc'?1:-1;
            table.reload('table', {initSort: obj,where: {sort: obj.field,order: order }});
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function(obj){
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for(var index=0;index<data.length;index++)
            {
                ids.push(data[index]._id)
            }
            switch(obj.event) {
                case 'async':
                    asyncRow();
                    break;
                case 'async-common':
                    asyncCommonMedia();
                    break;
                case 'up':
                    doRow(ids,'up');
                    break;
                case 'update':
                    updateRow(ids);
                    break;
                case 'clearTag':
                    doRow(ids,'clearTag');
                    break;
                case 'es':
                    doRow(ids,'es');
                    break;
                case 'down':
                    doRow(ids,'down');
                    break;
                case 'del':
                    doRow(ids,'del');
                    break;
                case 'adminLogs':
                    adminLogs();
                    break;
            }
        });
        /*表格-行事件*/
        table.on('tool(table)', function(obj){
            var data = obj.data;
            switch (obj.event) {
                case 'edit':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/movie/detail'); ?>?_id="+data._id,
                        area:  ['90%', '80%']
                    });
                    break;
                case 'more_link':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/movie/moreLink'); ?>?_id="+data._id,
                        area:  ['90%', '80%']
                    });
                    break;
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids,'del');
                    break;
                case 'comment':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/comment/movie'); ?>?object_id="+data._id,
                        area:  ['90%', '80%']
                    });
                    break;
            }
        });

        //监听其他事件
        util.event('lay-active', {
            tag: function(e){
                $('.layui-btn-sm-tag').addClass('layui-btn-primary');
                e.removeClass('layui-btn-primary');
                $("#tag").val(e.attr('data-id'));
            }
        });

        //操作
        function doRow(ids,act) {
            if(ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?",function() {
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/movie/do')?>",{act:act,id:ids.join(",")},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        showSuccessMsg("操作成功!请手动刷新页面");
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }

        //同步
        function asyncRow() {
            layerIndex=layer.open({
                title: '媒资库影片同步',
                type: 2,
                shade: 0.8,
                content: "<?php echo createUrl('/movie/widget'); ?>?type=async",
                area: ['800px', '600px'],
            });
        }


        //同步
        function asyncCommonMedia() {
            layer.prompt({
                formType: 2,
                value: '',
                title: '请输入公共媒资库视频ID',
                area: ['500px', '300px']
            }, function(value, index, elem){
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/movie/asyncCommon')?>",{id:value},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        layer.close(index);
                        showSuccessMsg("同步成功!请手动刷新页面");
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }

        //签到
        function adminLogs() {
            showConfirmMsg("确定操作吗?",function() {
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/system/adminLogs')?>",{},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        showSuccessMsg("签到成功!");
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }

        //批量设置
        function updateRow(ids) {
            ids=ids.join(',');
            if(ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            layerIndex=layer.open({
                type: 2,
                shade: 0.8,
                content: "<?php echo createUrl('/movie/update'); ?>?ids="+ids,
                area: ['85%', '80%'],
            });
        }
    })
</script>
