<?php

declare(strict_types=1);

namespace App\Controller;

use App\Constants\StatusCode;
use App\Core\Controller\BaseController;
use App\Exception\BusinessException;
use App\Repositories\Backend\AdminUserRepository;

/**
 * Class BaseBackendController
 * @package App\Controller
 */
class BaseBackendController extends BaseController
{
    /**
     * @var $adminUserRepo AdminUserRepository
     */
    protected $adminUserRepo = null;

    const NO_LOGIN_CONTROLLERS = array(
        '\App\Controller\Backend\LoginController'
    );

    protected $token = null;

    /**
     * 获取管理操作仓库
     * @return AdminUserRepository
     */
    protected function getAdminUserRepo()
    {
        if($this->adminUserRepo==null){
            $this->adminUserRepo = container()->get(AdminUserRepository::class);
        }
        return $this->adminUserRepo;
    }

    /**
     * 获取token
     * @return array
     */
    protected function getToken()
    {
        if (empty($this->token)) {
            $this->token = $this->getAdminUserRepo()->getToken();
        }
        return $this->token;
    }

    /**
     * 检查权限
     * @param $path
     */
    protected function checkPermission($path)
    {
        if(!$this->getAdminUserRepo()->checkPermission($path)){
            $this->sendErrorResult('无权操作!');
        }
    }

    /**
     * 初始化
     */
    public function initialize()
    {
        $this->token = $this->getToken();
        $controllerName = container()->get('dispatcher')->getControllerClass();
        if (!in_array($controllerName, self::NO_LOGIN_CONTROLLERS)) {
            $ip = getClientIp();
            if (empty($this->token) /*|| $this->token['ip'] != $ip  //bug 不能判断ip 会重复重定向*/) {
                $this->redirect('/login');
            }
        }
        $configs=getConfigs();
        $this->view->setVar('configs',$configs);
        $this->view->setVar('mediaUrl',$configs['media_url']);
        $this->view->setVar('mediaUrlVideo',$configs['media_url_video']?:$configs['media_url']);

        $this->view->setVar('uploadUrl',$configs['upload_url'].'/tools/upload?key='.$configs['media_key']);
        $this->view->setVar('uploadVideoUrl',$configs['upload_url'].'/upload/byte?key='.$configs['media_key']);
        $this->view->setVar('uploadVideoQueryUrl',$configs['upload_url'].'/upload/query?key='.$configs['media_key']);

        $this->view->setVar('systemName',$configs['system_name']);
        $this->view->setVar('username',$this->token['username']);
        $this->view->setVar('appid',container()->get('config')->app->name);
    }

    protected function sendSuccessResult($data = null)
    {
        $this->_addAdminLog();
        parent::sendSuccessResult($data); // TODO: Change the autogenerated stub
    }

    private function _addAdminLog()
    {
        if(!$this->isPost()){return;}
        $dispatcher = container()->get('dispatcher');
        $controllerName = $dispatcher->getControllerName();
        $actionName = $dispatcher->getActionName();
        if(in_array($controllerName,['feedback'])){return;}
        if(in_array($actionName,['save'])){
            $this->getAdminUserRepo()->adminUserService->addAdminLog("save action ".json_encode($_REQUEST));
        }elseif (in_array($actionName,['do'])){
            $this->getAdminUserRepo()->adminUserService->addAdminLog("do action ".json_encode($_REQUEST));
        }
    }
}