<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id"  placeholder="" autocomplete="off" class="layui-input">
                        <input type="hidden" name="imgs">
                        <input type="hidden" name="type" value="<?php echo $type;?>" placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">标题</label>
                            <div class="layui-input-block">
                                <input type="text" name="title" lay-verify="required" placeholder="" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <?php if($type=='game'):?>
                            <div class="layui-form-item">
                                <label class="layui-form-label">属性</label>
                                <div class="layui-input-block">
                                    <textarea name="params" placeholder="请输入" class="layui-textarea layui-content"></textarea>
                                </div>
                                <div class="layui-input-block">多个换行</div>
                            </div>
                            <div class="layui-form-item">
                                <label class="layui-form-label layui-form-required">下载地址</label>
                                <div class="layui-input-block">
                                    <input type="text" name="download_link" lay-verify="required" placeholder="" autocomplete="off" class="layui-input">
                                </div>
                            </div>
                            <div class="layui-form-item">
                                <label class="layui-form-label">推荐指数</label>
                                <div class="layui-input-block">
                                    <input type="number" class="layui-input" name="score" placeholder="">
                                </div>
                            </div>

                        <?php else:?>
<!--                            <div class="layui-form-item">-->
<!--                                <label class="layui-form-label layui-form-required">妹子编号</label>-->
<!--                                <div class="layui-input-block">-->
<!--                                    <input type="text" name="number" lay-verify="required" placeholder="" autocomplete="off" class="layui-input">-->
<!--                                </div>-->
<!--                            </div>-->
<!--                            <div class="layui-form-item">-->
<!--                                <label class="layui-form-label layui-form-required">标签</label>-->
<!--                                <div class="layui-input-block">-->
<!--                                    <select name="tag" lay-search>-->
<!--                                        <option value="">请选择..</option>-->
<!--                                        --><?php //foreach ($tagArr as $item): ?>
<!--                                            <option value="--><?php //echo $item; ?><!--">--><?php //echo $item; ?><!--</option>-->
<!--                                        --><?php //endforeach; ?>
<!--                                    </select>-->
<!--                                </div>-->
<!--                            </div>-->
                            <div class="layui-form-item">
                                <label class="layui-form-label layui-form-required">用户ID:</label>
                                <div class="layui-input-block">
                                    <input name="user_id" placeholder="请输入用户ID" class="layui-input" type="number" lay-verType="tips" lay-verify="required|number" required/>
                                </div>
                            </div>
                            <div class="layui-form-item">
                                <label class="layui-form-label layui-form-required">城市</label>
                                <div class="layui-input-block">
                                    <select name="city" lay-search>
                                        <option value="">请选择..</option>
                                        <?php foreach ($cityArr as $key=>$item): ?>
                                            <option value="<?php echo ($key); ?>"><?php echo $item; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="layui-form-item">
                                <label class="layui-form-label layui-form-required">服务价格</label>
                                <div class="layui-input-block">
                                    <input type="text" name="price" placeholder="" autocomplete="off" class="layui-input">
                                </div>
                            </div>
                            <div class="layui-form-item">
                                <label class="layui-form-label layui-form-required">联系方式</label>
                                <div class="layui-input-block">
                                    <input type="text" name="contact" placeholder="" autocomplete="off" class="layui-input">
                                </div>
                            </div>
                        <?php endif;?>
                        <div class="layui-form-item">
                            <label class="layui-form-label">简介</label>
                            <div class="layui-input-block">
                                <textarea name="description" rows="4"  maxlength="500" placeholder="请输入"  class="layui-textarea"></textarea>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">封面</label>
                            <div class="layui-input-block">
                                <div id="imgX" class="adv-type-image upload-select-picture-card" style="margin-left: 8px">
                                    <span class="layui-icon layui-icon-addition"></span>
                                </div>
                                <input name="img_x" id="imgXInput" value="" type="hidden" class="layui-input"/>
                            </div>
                        </div>
                        <div class="layui-form-item batch">
                            <label class="layui-form-label layui-form-required">图集</label>
                            <div style="display: block" class="layui-input-block  upload-container">
                                <div>
                                    <div class="add" id="photos">
                                        <span class="layui-icon layui-icon-addition"></span>
                                    </div>
                                </div>
                                <div class="upload-select-picture-cards">
                                    <div class="cares" style="display: flex;flex-wrap: wrap;">
                                        <?php foreach ($row['images'] as $key=>$val):?>
                                            <div style="margin-bottom: 8px" class="card-item">
                                                <input type="hidden" lay-verify="required" required name="images[]" value="<?php echo $val;?>">
                                                <a target="_blank" href="<?php echo $mediaUrl.$val;?>"><img width="102" height="102" src="<?php echo $mediaUrl.$val;?>"></a>
                                                <i class="del layui-icon layui-icon-close" lay-active="del"></i>
                                            </div>
                                        <?php endforeach;?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="layui-row select-type select-type1">
                            <div class="layui-col-md6">
                                <div class="layui-form-item">
                                    <label class="layui-form-label">视频地址</label>
                                    <div class="layui-input-block">
                                        <input type="text" name="video"  placeholder="" autocomplete="off" class="layui-input video-input">
                                    </div>
                                </div>
                            </div>
                            <div class="layui-col-md6 select-type select-type1">
                                <div class="layui-form-item">
                                    <label class="layui-form-label">视频时长</label>
                                    <div class="layui-input-block">
                                        <input type="text" name="duration"  placeholder="" autocomplete="off" class="layui-input">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="layui-row select-type select-type1">
                            <div class="layui-col-md6">
                                <div class="layui-form-item">
                                    <label class="layui-form-label"></label>
                                    <div class="layui-input-block">
                                        <video style="height: 300px;width: 100%;background-color: #555" class="video-player" id="videoElement" controls></video>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">金币:</label>
                            <div class="layui-input-block">
                                <input type="text" name="money" value="0"  placeholder="" autocomplete="off" class="layui-input">
                                <div class="layui-form-mid layui-word-aux">金币>0 免费<=0</div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">排序:</label>
                            <div class="layui-input-block">
                                <input name="sort" placeholder="请输入排序" class="layui-input" type="number" value="0" lay-verType="tips" lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">审核状态</label>
                            <div class="layui-input-block">
                                <?php foreach ($statusArr as $key=>$val):?>
                                    <input lay-filter="select-status" type="radio" <?php if($key==1):?>checked<?php endif;?> name="status" value="<?php echo $key;?>" title="<?php echo $val;?>" >
                                <?php endforeach;?>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php  echo createStaticUrl('/admin/default/assets/js/hls.min.js'); ?>"></script>
<script>
    layui.use(['index', 'form','upload','util'], function(){
        var $ = layui.$
            ,element = layui.element
            ,upload = layui.upload
            ,util = layui.util
            ,form = layui.form;
        form.val('info-form',<?php echo json_encode($row);?>);
        form.render(null, 'info-form');

        if(form.val("info-form").img_x){
            $("#imgX").html("<img width='102' height='102' src='<?php echo $mediaUrl;?>"+form.val("info-form").img_x+"'>");
        }

        element.render('breadcrumb', 'breadcrumb');

        upload.render({
            elem: '#imgX' //绑定元素
            ,url: '<?php echo $mediaUrl.'/api/tools/upload'; ?>' //上传接口
            ,done: function(res){
                $("#imgX").html("<img width='102' height='102' src='<?php echo $mediaUrl;?>"+res.data+"'>");
                $("#imgXInput").val(res.data);
            }
            ,error: function(){
                //请求异常回调
            }
        });

        //多图上传
        upload.render({
            elem: '#photos' //绑定元素
            ,url: '<?php echo $mediaUrl.'/api/tools/upload'; ?>' //上传接口
            ,multiple: true
            ,done: function(res){
                var html= [
                    '<div style="margin-bottom: 8px" class="card-item">',
                    '<input type="hidden" lay-verify="required" required name="images[]" value="'+res.data+'">',
                    '<a target="_blank" href="<?php echo $mediaUrl;?>'+res.data+'"><img width="102" height="102" src="<?php echo $mediaUrl;?>'+res.data+'"></a>',
                    '<i class="del layui-icon layui-icon-close" lay-active="del"></i>',
                    '</div>',
                ].join('');
                $(".upload-select-picture-cards .cares").append(html);
            }
            ,error: function(){
                //请求异常回调
            }
        });
        util.event('lay-active', {
            del: function(e){
                $(e).parent().remove();
            }
        });

        if(form.val("info-form").video){
            initPlay();
        }
        $('.video-input').blur(function () {
            initPlay();
        })
        function initPlay(){
            var url = "<?php echo $mediaUrl;?>"+form.val("info-form").video;
            var video = document.getElementById('videoElement');
            //var poster = "<?php //echo $mediaUrl;?>//"+form.val("info-form").img_x;
            //video.attr('poster',poster)

            if (video.canPlayType('application/vnd.apple.mpegurl')) {
                video.src = url;
            } else if (Hls.isSupported()) {
                var hls = new Hls();
                hls.loadSource(url);
                hls.attachMedia(video);
            } else {
                alert('抱歉，您的浏览器不支持hls视频播放器，请更换浏览器尝试！')
            }
        }

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/play/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
