<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <input type="hidden" name="type" value="<?php echo $type;?>">
                    <div class="layui-inline">
                        <label class="layui-form-label">ID:</label>
                        <div class="layui-input-inline">
                            <input name="_id" class="layui-input"  autocomplete="off" placeholder="请输入ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">名称:</label>
                        <div class="layui-input-inline">
                            <input name="title" class="layui-input"  autocomplete="off" placeholder="请输入名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">用户id:</label>
                        <div class="layui-input-inline">
                            <input name="user_id" class="layui-input"  autocomplete="off" placeholder="请输入用户id"/>
                        </div>
                    </div>
                    <?php if($type!='game'):?>
<!--                    <div class="layui-inline">-->
<!--                        <label class="layui-form-label">编号:</label>-->
<!--                        <div class="layui-input-inline">-->
<!--                            <input name="number" class="layui-input"  autocomplete="off" placeholder="请输入编号"/>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="layui-inline">-->
<!--                        <label class="layui-form-label">标签:</label>-->
<!--                        <div class="layui-input-inline">-->
<!--                            <select name="tag" lay-search>-->
<!--                                <option value="">请选择..</option>-->
<!--                                --><?php //foreach ($tagArr as $item): ?>
<!--                                    <option value="--><?php //echo $item; ?><!--">--><?php //echo $item; ?><!--</option>-->
<!--                                --><?php //endforeach; ?>
<!--                            </select>-->
<!--                        </div>-->
<!--                    </div>-->
                        <div class="layui-inline">
                            <label class="layui-form-label">状态:</label>
                            <div class="layui-input-inline">
                                <select name="status">
                                    <option value="">请选择..</option>
                                    <?php foreach ($statusArr as $key=>$item): ?>
                                        <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">购买类型:</label>
                            <div class="layui-input-inline">
                                <select name="pay_type">
                                    <option value="">请选择..</option>
                                    <?php foreach ($payTypeArr as $key=>$item): ?>
                                        <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">城市:</label>
                        <div class="layui-input-inline">
                            <select name="city" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($cityArr as $key=>$item): ?>
                                    <option value="<?php echo ($key); ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <?php endif;?>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
                    <button class="layui-btn layui-btn-xs" lay-event="add">添加</button>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>
                    <button class="layui-btn layui-btn-xs " lay-event="update">批量设置</button>
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
                <!--<a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="comment">评论</a>-->
                <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,$;
    layui.use(['layer', 'form', 'table', 'admin'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:30
                ,limits:[10,30,50,100,500,1000]
            }
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {type: 'checkbox'}
                ,{field:'_id', title: 'ID',align: 'center', width: 70, sort:true}
                ,{field: 'user_info', title:'用户信息', templet: function (row) {
                        var str='';
                        if(row.is_system==1){
                            str= "<p style='color: red'>"+row.user_id+"</p>"+"<p style='color: red'>"+row.nickname+"("+row.user_sex+")</p>"
                        }else {
                            str="<p >"+row.user_id+"</p>"+"<p>"+row.nickname+"("+row.user_sex+")</p>";
                        }
                        str+="<p>用户组:"+row.group_name+"</p>";
                        // str+="<p style='color:red'>是否UP:"+row.up_text+"</p>";
                        // str+="<p>是否商家:"+row.user_text+"</p>";
                        return str;
                    },width:150,align: 'center'}
                ,{field: 'head', title:'用户头像', width: 60, templet: function (row) {
                        if(row.head){
                            var link='<?php echo $mediaUrl;?>'+row.head;
                            return '<a target="_blank" href="'+link+'" ><img src="'+link+'" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="max-width: 50px;max-height: 50px"/></a>'
                        }
                        return '-';
                    },align: 'center'}
                ,{field:'title', title: '名称',align: 'center'}
                ,{field: 'images', title:'图集',align: 'center', templet: function (row) {
                        var postImgs = '';
                        $.each(row.images,function (i,e) {
                            e = '<?php echo $mediaUrl;?>'+e;
                            postImgs += '<a target="_blank" href="'+e+'" ><img src="'+e+'" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="width: 33px;height: 33px;margin-left:6px;margin-top:6px;"/></a>';
                        });
                        return postImgs?postImgs:'-';
                    }, width: 120}

                <?php if($type=='game'):?>
                ,{field:'download_link', title: '下载链接',align: 'center'}
                ,{field:'score', title: '推荐指数',templet: function (row) {
                        return row.score?row.score:'-';
                    },align: 'center', sort:true}
                <?php else:?>
                // ,{field:'number', title: '编号',align: 'center'}
                // ,{field:'tag', title: '标签',align: 'center'}
                ,{field:'city', title: '城市',templet: function (row) {
                        return row.city?row.city:'-';
                    },align: 'center'}
                <?php endif;?>

                ,{field:'pay_type', title: '购买类型',width:80,align: 'center',style:'color:red',templet:function (row) {
                    if(row.pay_type=='money'){
                        return row.pay_type+" ￥:"+row.money;
                    }
                    return row.pay_type;
                }}
                ,{field: 'real_click', title: '点击',align: 'center',width: 60, sort:true}
                ,{field: 'real_favorite', title: '收藏',align: 'center',width: 60, sort:true}
                ,{field: 'status', title: '状态',align: 'center',width: 50}
                ,{field:'sort', title: '排序',align: 'center', sort:true}
                ,{field:'created_at', title: '创建时间',align: 'center'}
                ,{title:'操作', toolbar: '#table-item-toolbar',align: 'center', width:150}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function(obj){
            var order=obj.type==='asc'?1:-1;
            table.reload('table', {initSort: obj,where: {sort: obj.field,order: order }});
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function(obj){
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for(var index=0;index<data.length;index++)
            {
                ids.push(data[index]._id)
            }
            switch(obj.event) {
                case 'add':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/play/detail'); ?>?type=<?php echo $type;?>",
                        area:  ['80%', '80%']
                    });
                    break;
                case 'del':
                    doRow(ids,'del');
                    break;
                case 'update':
                    updateRow(ids);
                    break;
            }
        });
        /*表格-行事件*/
        table.on('tool(table)', function(obj){
            var data = obj.data;
            switch (obj.event) {
                case 'comment':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/comment/play'); ?>?object_id="+data._id,
                        area:  ['80%', '80%']
                    });
                    break;
                case 'edit':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/play/detail'); ?>?_id="+data._id+"&type=<?php echo $type;?>",
                        area:  ['80%', '80%']
                    });
                    break;
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids,'del');
                    break;
            }
        });
        function doRow(ids,act) {
            if(ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?",function() {
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/play/do')?>",{act:act,id:ids.join(",")},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }
        //批量设置
        function updateRow(ids) {
            ids=ids.join(',');
            if( ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            layerIndex=layer.open({
                type: 2,
                shade: 0.8,
                content: "<?php echo createUrl('/play/update'); ?>?ids="+ids+"&type=<?php echo $type;?>",
                area: ['1000px', '80%'],
            });
        }
    })
</script>
