<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">资源类型</label>
                            <div class="layui-input-block">
                                <?php foreach ($sourceArr as $key=>$item): ?>
                                    <input type="radio" name="source" value="<?php echo $key; ?>" title="<?php echo $item; ?>" <?php if($key=='media'):?>checked<?php endif?> >
                                <?php endforeach; ?>
                            </div>
                        </div>
<!--                        <div class="layui-form-item">-->
<!--                            <label class="layui-form-label layui-form-required">用户ID</label>-->
<!--                            <div class="layui-input-block">-->
<!--                                <input type="text" name="user_id" lay-verify="required" placeholder="" autocomplete="off" class="layui-input">-->
<!--                            </div>-->
<!--                        </div>-->
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">媒资库ID</label>
                            <div class="layui-input-block">
                                <textarea name="id" rows="5"  maxlength="1000" style="height: 300px;" placeholder="请输入" lay-verify="required"  class="layui-textarea"></textarea>
                            </div>
                            <div class="layui-input-block">请输入媒资库视频ID,一行一个</div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form'], function(){
        var $ = layui.$,element = layui.element,form = layui.form;
        form.render(null, 'info-form');
        element.render('breadcrumb', 'breadcrumb');

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/movie/async')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status=='y'){
                    parent.layer.close(parent.layerIndex);
                    showSuccessMsg("同步成功!请手动刷新页面");
                }else{
                    showErrorMsg(res.error);
                }
            });
            return false;
        });
    });
</script>
