<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">兑换码详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id"  placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">名称:</label>
                            <div class="layui-input-block">
                                <input name="name" placeholder="请输入名称" class="layui-input"  autocomplete="off"  lay-verType="tips"
                                       lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">兑换码类型:</label>
                            <div class="layui-input-block">
                                <?php foreach ($codeTypes as $key=>$val):?>
                                    <input name="type" lay-filter="select-type-change" type="radio" <?php if ($key=='group'):?>checked<?php endif;?> value="<?php echo $key;?>" title="<?php echo $val;?>"/>
                                <?php endforeach;?>
                            </div>
                        </div>
                        <div class="layui-form-item code-group">
                            <label class="layui-form-label layui-form-required">会员套餐:</label>
                            <div class="layui-input-block">
                                <select name="vip_id">
                                    <option value="">请选择..</option>
                                    <?php foreach ($userGroups as $userGroup):?>
                                        <option value="<?php echo $userGroup['id'];?>"><?php echo $userGroup['id'].' | '.$userGroup['name'];?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item code-point">
                            <label class="layui-form-label layui-form-required">金币套餐:</label>
                            <div class="layui-input-block">
                                <select name="coin_id">
                                    <option value="">请选择..</option>
                                    <?php foreach ($productGroups as $productGroup):?>
                                        <option value="<?php echo $productGroup['id'];?>"><?php echo $productGroup['id'].' | '.$productGroup['name'];?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required ">数量:</label>
                            <div class="layui-input-block">
                                <input name="num" placeholder="请输入数量" value=""  type="number" autocomplete="off" class="layui-input" lay-verType="tips" lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">过期时间:</label>
                            <div class="layui-input-block">
                                <input name="expired_at" id="expired_at" placeholder="请输入过期时间"   autocomplete="off"  value="" type="text" class="layui-input icon-date" lay-verType="tips" lay-verify="required" required />
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required ">可使用次数:</label>
                            <div class="layui-input-block">
                                <input name="can_use_num" placeholder="请输入可使用次数" value=""  autocomplete="off"  type="number" class="layui-input" lay-verType="tips" lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required ">数量（天数/金币）:</label>
                            <div class="layui-input-block">
                                <input name="add_num" placeholder="请输入兑换数量" value="" type="number"  autocomplete="off"  class="layui-input" lay-verType="tips" lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required ">谷歌验证码:</label>
                            <div class="layui-input-block">
                                <input name="google_code" placeholder="请输入谷歌验证码" value="" type="text"  autocomplete="off"  class="layui-input" lay-verType="tips" lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form', 'upload', 'laydate'], function(){
        var $ = layui.$
            ,element = layui.element
            ,upload = layui.upload
            ,form = layui.form
            ,laydate = layui.laydate
            ,row = <?php echo json_encode($row);?>;

        form.val('info-form', row);
        form.render(null, 'info-form');

        element.render('breadcrumb', 'breadcrumb');

        var type = row&&row.type?row.type:'group';
        showType(type);

        //时间
        laydate.render({
            elem: '#expired_at',
            type: 'datetime'
        });

        //选择类型
        form.on('radio(select-type-change)', function(data){
            showType(data.value);
        });
        function showType(type)
        {
            if(type==='point'){
                $(".code-point").show();
                $(".code-group").hide();
            }else{
                $(".code-point").hide();
                $(".code-group").show();
            }
        }

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/userCode/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
