<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">兑换码名称:</label>
                        <div class="layui-input-inline">
                            <input name="name" class="layui-input" placeholder="请输入兑换名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">兑换码:</label>
                        <div class="layui-input-inline">
                            <input name="code" class="layui-input" placeholder="请输入兑换码"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID:</label>
                        <div class="layui-input-inline">
                            <input name="user_id" class="layui-input" placeholder="请输入用户ID"/>
                        </div>
                    </div>
<!--                    <div class="layui-inline">-->
<!--                        <label class="layui-form-label">用户名:</label>-->
<!--                        <div class="layui-input-inline">-->
<!--                            <input name="username" class="layui-input" placeholder="请输入用户名"/>-->
<!--                        </div>-->
<!--                    </div>-->
                    <div class="layui-inline">
                        <label class="layui-form-label">类型:</label>
                        <div class="layui-input-inline">
                            <select name="type">
                                <option value="">请选择..</option>
                                <?php foreach ($codeTypes as $key=>$val):?>
                                    <option value="<?php echo $key;?>"><?php echo $val;?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,$;
    layui.use(['layer', 'table', 'admin'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:30
                ,limits:[10,30,50,100]
            }
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {type: 'checkbox'}
                ,{field:'_id', title: 'ID',align: 'center', width: 100, sort:true}
                ,{field: 'name', title: '名称',align: 'center'}
                ,{field: 'code', title: '兑换码',align: 'center'}
                ,{field: 'username', title: '用户名',align: 'center'}
                ,{field: 'type_text', title: '类型',align: 'center'}
                ,{field: 'object_name', title: '资源名称',align: 'center'}
                ,{field: 'add_num', title: '数量',align: 'center'}
                ,{field: 'created_at', title: '创建时间',align: 'center'}
                ,{field: 'updated_at', title: '更新时间',align: 'center'}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function(obj){
            var order=obj.type==='asc'?1:-1;
            table.reload('table', {initSort: obj,where: {sort: obj.field,order: order }});
        });
    })
</script>
