<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label"><?php echo $object_title;?>ID:</label>
                        <div class="layui-input-inline">
                            <input name="object_id" value="<?php echo $object_id?:'';?>" class="layui-input"  autocomplete="off" placeholder="请输入资源ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID:</label>
                        <div class="layui-input-inline">
                            <input name="from_uid" value="" class="layui-input"  autocomplete="off" placeholder="请输入用户ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">内容:</label>
                        <div class="layui-input-inline">
                            <input name="content" value="" class="layui-input"  autocomplete="off" placeholder="请输入评论内容"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">状态:</label>
                        <div class="layui-input-inline">
                            <select name="status">
                                <option value="">请选择..</option>
                                <option value="0">已删除</option>
                                <option value="1" selected>正常</option>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
                    <?php if($object_id):?>
                        <button class="layui-btn layui-btn-xs layui-btn-normal" lay-event="add">发布评论</button>
                    <?php endif;?>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="delAndDis">删除+禁用</button>
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
                <a class="layui-btn layui-btn-xs" lay-event="show">查看回复</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,$;
    layui.use(['layer', 'form', 'table', 'admin'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:50
                ,limits:[10,30,50,100]
            }
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {type: 'checkbox'}
                ,{field:'_id', title: 'ID',align: 'center',sort:true, width:150}
                ,{field:'object_id', title: '<?php echo $object_title;?>ID',align: 'center', width:150,sort:true}
                ,{field:'from_uid', title: '用户ID',align: 'center',sort:true, width:100}
                ,{field:'nickname', title: '用户昵称',align: 'center', width:100}
                ,{field:'content', title: '评论内容',align: 'center', width:300,templet:function (item) {
                    var html='';
                    //删除
                    if(item.status===1){
                        html+='<p class="message-text">'+item.content+'</p>'
                    }else{
                        html+='<p class="message-text" style="text-decoration:line-through;color: red">(已删除)'+item.content+'</p>'
                    }
                    return html;
                }}
                ,{field:'child_num', title: '回复数量',align: 'center',sort:true}
                ,{field:'status_label', title: '状态',align: 'center'}
                ,{field:'created_at', title: '创建时间',align: 'center',sort:true}
                ,{title:'操作', toolbar: '#table-item-toolbar',align: 'center', width:150}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function(obj){
            var order=obj.type==='asc'?1:-1;
            table.reload('table', {initSort: obj,where: {sort: obj.field,order: order }});
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function(obj){
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for(var index=0;index<data.length;index++)
            {
                ids.push(data[index]._id)
            }
            switch(obj.event) {
                case 'add':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/comment/comment'); ?>?object_id=<?php echo $object_id;?>&object_type=<?php echo $object_type;?>",
                        area:  ['80%', '80%']
                    });
                    break;
                case 'del':
                    doRow(ids,'del');
                    break;
                case 'delAndDis':
                    doRow(ids,'delAndDis');
                    break;
            }
        });
        /*表格-行事件*/
        table.on('tool(table)', function(obj){
            var data = obj.data;
            switch (obj.event) {
                case 'show':
                    layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/commentReply/reply'); ?>?_id="+data._id,
                        area:  ['80%', '80%']
                    });
                    break;
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids,'del');
                    break;
                case 'reply'://发布评论或回复
                    var commentId=data._id;
                    var type='comment';
                    if(data.reply_type=='comment'||data.reply_type=='reply'){
                        commentId=data._id;
                        type='reply';
                    }
                    admin.open({
                        type: 1,
                        area: ['800px', '50%'],
                        title:'回复评论：'+data.content,
                        content: laytpl($('#replyDialog').html()).render({}),
                        success: function (layero, dIndex) {
                            // 表单提交事件
                            form.on('submit(btnReplySubmit)', function (datas) {
                                datas.field.comment_id=commentId;
                                datas.field.type=type;
                                doLoadAjax("<?php  echo createUrl('/comment/doReply');?>", datas.field, function (res) {
                                    if (res.status === 'y') {
                                        layer.close(dIndex);
                                        location.reload();
                                    } else {
                                        showErrorMsg(res.error);
                                    }
                                });
                                return false;
                            });
                            // 禁止弹窗出现滚动条
                            $(layero).children('.layui-layer-content').css('overflow', 'visible');
                        }
                    });
                    break;
            }
        });
        function doRow(ids,act) {
            if(ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?",function() {
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/comment/do')?>",{act:act,id:ids.join(","),table:'comment'},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }
    })
</script>
