<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">菜单详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id"  placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">权限名称:</label>
                            <div class="layui-input-block">
                                <input name="name" placeholder="请输入权限名称" class="layui-input" lay-verType="tips"
                                       lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">上级菜单</label>
                            <div class="layui-input-block">
                                <select name="parent_id" lay-verType="tips" lay-verify="required" required>
                                    <option value="">请选择上级菜单</option>
                                    <option value="0">顶级菜单</option>
                                    <?php echo $options; ?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">权限类型:</label>
                            <div class="layui-input-block">
                                <input name="is_menu" type="radio" value="1" title="菜单" checked/>
                                <input name="is_menu" type="radio" value="0" title="按钮"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">权限标识:</label>
                            <div class="layui-input-block">
                                <input name="key" placeholder="请输入权限标识" class="layui-input"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label ">菜单url:</label>
                            <div class="layui-input-block">
                                <input name="link" placeholder="请输入url" class="layui-input"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">菜单图标:</label>
                            <div class="layui-input-block">
                                <input name="class_name" placeholder="请输入菜单图标" class="layui-input"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">排序:</label>
                            <div class="layui-input-block">
                                <input name="sort" placeholder="请输入排序" type="number" value="0" class="layui-input"
                                       lay-verType="tips">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form'], function(){
        var $ = layui.$
            ,element = layui.element
            ,form = layui.form;
        form.val('info-form',<?php echo json_encode($row);?>);
        form.render(null, 'info-form');

        element.render('breadcrumb', 'breadcrumb');

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/authority/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
