<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">分类详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id"  placeholder="" autocomplete="off" class="layui-input">
                        <input type="hidden" id="image_size" name="size"  placeholder="" autocomplete="off" class="layui-input">
                        <input type="hidden" name="position"  placeholder="" value="<?php echo $position;?>" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="name" lay-verify="required" placeholder="" autocomplete="off" class="layui-input">
                            </div>
                        </div>

                        <?php if (!empty($catArr)):?>
                        <div class="layui-form-item">
                            <label class="layui-form-label">分类</label>
                            <div class="layui-input-block">
                                <?php foreach ($catArr as $key=>$item):?>
                                    <input type="checkbox" name="categories[]" <?php if($row['categories']&&in_array($item['id'],$row['categories'])):?>checked<?php endif;?>  value="<?php echo $item['id'];?>" lay-skin="primary" title="<?php echo $item['name'];?>">
                                <?php endforeach;?>
                            </div>
                        </div>
                        <?php endif;?>

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">图片:</label>
                            <div class="layui-input-block">
                                <div id="imgX" class="user-tag upload-select-picture-card">
                                    <span class="layui-icon layui-icon-addition"></span>
                                </div>
                                <input name="img" id="imgXInput"  value="" type="text" class="layui-input" style="display: none" />
                            </div>
                        </div>

                        <div class="layui-col-md12">
                            <div class="layui-form-item">
                                <label class="layui-form-label layui-form-required">金币</label>
                                <div class="layui-input-block">
                                    <input name="money" placeholder="" class="layui-input" type="number" value="0" lay-verType="tips" lay-verify="required" required/>
                                </div>
                            </div>
                        </div>

                        <?php if(!empty($row['video'])):?>
                            <div class="layui-form-item">
                                <label class="layui-form-label">视频:</label>
                                <div class="layui-input-block">
                                    <video controls="controls" data-url="<?php echo $mediaUrlVideo.$row['video'];?>" style="max-width:800px;max-height: 500px" id="videoPlayer"></video>
                                </div>
                            </div>
                        <?php endif;?>

<!--                        <div class="layui-form-item">-->
<!--                            <label class="layui-form-label">热门</label>-->
<!--                            <div class="layui-input-block">-->
<!--                                --><?php //foreach ($hot as $key=>$item): ?>
<!--                                    <input type="radio" name="is_hot" value="--><?php //echo $key; ?><!--" title="--><?php //echo $item; ?><!--" --><?php //if($key==0):?><!--checked--><?php //endif?><!-- >-->
<!--                                --><?php //endforeach; ?>
<!--                            </div>-->
<!--                        </div>-->
                        <div class="layui-form-item">
                            <label class="layui-form-label">提示文字:</label>
                            <div class="layui-input-block">
                                <input name="tips" placeholder="" class="layui-input" type="text" value=""/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">排序:</label>
                            <div class="layui-input-block">
                                <input name="sort" placeholder="请输入排序" class="layui-input" type="number" value="0" lay-verType="tips" lay-verify="required" required/>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">是否18禁</label>
                            <div class="layui-input-block">
                                <?php foreach ($hot as $key=>$item): ?>
                                    <input type="radio" name="is_porn" value="<?php echo $key; ?>" title="<?php echo $item; ?>" <?php if($key==1):?>checked<?php endif?> >
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php foreach ($disabled as $key=>$item): ?>
                                    <input type="radio" name="is_disabled" value="<?php echo $key; ?>" title="<?php echo $item; ?>" <?php if($key==0):?>checked<?php endif?> >
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php  echo createStaticUrl('/admin/default/assets/js/hls.min.js'); ?>"></script>

<script>
    layui.use(['index', 'form', 'upload'], function(){
        var $ = layui.$
            ,element = layui.element
            ,upload = layui.upload
            ,form = layui.form
            ,row = <?php echo json_encode($row);?>;
        form.val('info-form',row);
        form.render(null, 'info-form');

        element.render('breadcrumb', 'breadcrumb');

        //回显部分数据
        if(row&&row.img){
            $("#imgX").html("<img width='102' height='102' src='<?php echo $mediaUrl;?>"+row.img+"'>");

            getImageSize("<?php echo $mediaUrl.$row['img'];?>")
                .then(size => {
                    console.log(size);
                    $('#image_size').val(size);
                })
                .catch(error => {
                    console.error(error);
                });
        }

        if(document.getElementById('videoPlayer')){
            var hlsTargetPathPlayer = new Hls();
            hlsTargetPathPlayer.loadSource(document.getElementById('videoPlayer').getAttribute('data-url')); // 传入路径
            hlsTargetPathPlayer.attachMedia(document.getElementById('videoPlayer'));
        }

        //上传图片
        upload.render({
            elem: '#imgX' //绑定元素
            ,url: '<?php echo $uploadUrl; ?>' //上传接口
            ,done: function(res){
                console.log(res);
                var item = this.elem;
                $("#imgX").html("<img width='102' height='102' src='<?php echo $mediaUrl;?>"+res.data+"'>");
                $("#imgXInput").val(res.data);
                getImageSize("<?php echo $mediaUrl;?>"+res.data)
                    .then(size => {
                        console.log(size);
                        $('#image_size').val(size);
                    })
                    .catch(error => {
                        console.error(error);
                    });
            }
            ,error: function(){
                //请求异常回调
            }
        });

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/aiResourceTemplate/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

        function getImageSize(imageUrl) {
            return new Promise((resolve, reject) => {
                const img = new Image();

                img.onload = function() {
                    resolve(`${img.width}x${img.height}`);
                };

                img.onerror = function() {
                    reject('Unable to load image');
                };

                img.src = imageUrl;
            });
        }

    });

</script>
