<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">名称:</label>
                        <div class="layui-input-inline">
                            <input name="name" class="layui-input"  autocomplete="off" placeholder="请输入名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">状态:</label>
                        <div class="layui-input-inline">
                            <select name="is_disabled">
                                <option value="">请选择..</option>
                                <?php foreach ($disabled as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">是否18禁:</label>
                        <div class="layui-input-inline">
                            <select name="is_porn">
                                <option value="">请选择..</option>
                                <?php foreach ($hot as $key=>$item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
                    <?php if(in_array($position,['face_image'])):?>
                    <button class="layui-btn layui-btn-xs" lay-event="add">添加</button>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>
                    <?php else:?>
                        <button class="layui-btn layui-btn-xs layui-btn-primary" lay-event="async">同步模版</button>
                    <?php endif;?>
                    <button class="layui-btn layui-btn-xs" lay-event="update">批量设置</button>
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
                <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                {{#  if(!d.aid){ }}
                <a id="btn-del" class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
                {{#  } }}
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,$;
    layui.use(['layer', 'form', 'table', 'admin'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:30
                ,limits:[10,30,50,100]
            }
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {type: 'checkbox'}
                ,{field:'_id', title: 'ID',align: 'center',sort:true}
                ,{field:'name', title: '名称',align: 'center'}
                ,{field: 'img', title:'图片',align: 'center', templet: function (row) {
                        if(row.img){
                            var link='<?php echo $mediaUrl;?>'+row.img;
                            return '<a target="_blank" href="'+link+'" ><img src="'+link+'" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="max-width: 66px;max-height: 200px"/></a>'
                        }
                        return '-';
                    }, width: 100}
                ,{field:'size', title: '图片尺寸',align: 'center'}
                ,{field: 'categories', title: '分类',align: 'center',width: 120}
                ,{field: 'money', title: '金币',style:'color:red',align: 'center',width: 50}
                ,{field: 'buy', title: '使用次数',align: 'center',sort:true}
                ,{field:'sort', title: '排序',align: 'center',sort:true}
                ,{field:'is_porn', title: '是否18禁',align: 'center'}
                ,{field:'is_disabled', title: '状态',align: 'center'}
                ,{field:'created_at', title: '创建时间',align: 'center'}
                ,{title:'操作', toolbar: '#table-item-toolbar',align: 'center', width:150}
            ]]
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function(obj){
            var order=obj.type==='asc'?1:-1;
            table.reload('table', {initSort: obj,where: {sort: obj.field,order: order }});
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function(obj){
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for(var index=0;index<data.length;index++)
            {
                ids.push(data[index]._id)
            }
            switch(obj.event) {
                case 'add':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/aiResourceTemplate/detail'); ?>?position=<?php echo $position;?>",
                        area:  ['1000px', '600px']
                    });
                    break;
                case 'del':
                    doRow(ids,'del');
                    break;
                case 'update':
                    updateRow(ids);
                    break;
                case 'async':
                    asyncRow();
                    break;
            }
        });
        /*表格-行事件*/
        table.on('tool(table)', function(obj){
            var data = obj.data;
            switch (obj.event) {
                case 'edit':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/aiResourceTemplate/detail'); ?>?_id="+data._id+"&position=<?php echo $position;?>",
                        area:  ['1000px', '600px']
                    });
                    break;
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids,'del');
                    break;
            }
        });
        function doRow(ids,act) {
            if(ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?",function() {
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/aiResourceTemplate/do')?>",{act:act,id:ids.join(",")},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }

        //批量设置
        function updateRow(ids) {
            ids=ids.join(',');
            if(ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            layerIndex=layer.open({
                type: 2,
                shade: 0.8,
                content: "<?php echo createUrl('/aiResourceTemplate/update'); ?>?ids="+ids+"&position=<?php echo $position;?>",
                area: ['90%', '80%'],
            });
        }

        //同步
        function asyncRow() {
            showConfirmMsg("确定操作吗?",function() {
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/aiResourceTemplate/async')?>"+"?position=<?php echo $position;?>",{},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        showSuccessMsg("成功"+res.data.success+"个模版，失败"+res.data.fail+"个模版!");
                        table.reload('table');
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }
    })
</script>
