<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">模块详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id"  placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">分区</label>
                            <div class="layui-input-block">
                                <?php foreach ($posArr as $key=>$item): ?>
                                    <input type="radio" name="position" value="<?php echo $key; ?>" title="<?php echo $item; ?>" <?php if($key=='all'):?>checked<?php endif?> >
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">名称:</label>
                            <div class="layui-input-block">
                                <input name="name" placeholder="请输入" autocomplete="off" class="layui-input" lay-verType="tips" lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">跳转链接:</label>
                            <div class="layui-input-block">
                                <input name="url" placeholder="请输入" autocomplete="off" class="layui-input"/>
                            </div>
                        </div>
                        <div class="layui-row">
                            <div class="layui-col-md6">
                                <div class="layui-form-item">
                                    <label class="layui-form-label">横图:</label>
                                    <div class="layui-input-block">
                                        <div id="imgX" class="adv-type-image upload-select-picture-card">
                                            <span class="layui-icon layui-icon-addition"></span>
                                        </div>
                                        <input name="img_x" id="imgXInput" value="" type="hidden" class="layui-input"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">支持最低版本:</label>
                            <div class="layui-input-block">
                                <input name="min_version" placeholder="请输入" autocomplete="off" class="layui-input"/>
                                <div class="layui-word-aux">
                                    大于填写的版本app才会展示该功能，不填写默认所有版本展示
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">角标:</label>
                            <div class="layui-input-block">
                                <input name="ico"  type="radio" value="" title="无" checked/>
                                <?php foreach ($icos as $k=>$v):?>
                                    <input name="ico"  type="radio" value="<?php echo $k;?>" title="<?php echo $v;?>"/>
                                <?php endforeach;?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">排序:</label>
                            <div class="layui-input-block">
                                <input name="sort" placeholder="请输入排序" autocomplete="off" class="layui-input"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">是否显示:</label>
                            <div class="layui-input-block">
                                <input name="is_disabled"  lay-filter="select-adv-type" type="radio" value="0" title="显示" checked/>
                                <input name="is_disabled"  lay-filter="select-adv-type" type="radio" value="1" title="关闭"/>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form','upload'], function(){
        var $ = layui.$
            ,element = layui.element
            ,upload = layui.upload
            ,form = layui.form;

        form.val('info-form',<?php echo json_encode($row);?>);
        form.render(null, 'info-form');
        element.render('breadcrumb', 'breadcrumb');
        if(form.val("info-form").img_x){
            $("#imgX").html("<img width='102' height='102' src='<?php echo $mediaUrl;?>"+form.val("info-form").img_x+"'>");
        }
        upload.render({
            elem: '#imgX' //绑定元素
            ,url: '<?php echo $uploadUrl; ?>' //上传接口
            ,done: function(res){
                $("#imgX").html("<img width='102' height='102' src='<?php echo $mediaUrl;?>"+res.data+"'>");
                $("#imgXInput").val(res.data);
            }
            ,error: function(){
                //请求异常回调
            }
        });
        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            doAjax("<?php echo createUrl('/aiBlock/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
