<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">状态:</label>
                        <div class="layui-input-inline">
                            <select name="status">
                                <option value="" selected></option>
                                <?php foreach ($statusArr as $k=>$v):?>
                                    <option value="<?php echo $k;?>"><?php echo $v;?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">是否显示:</label>
                        <div class="layui-input-inline">
                            <select name="is_disabled">
                                <option value="">请选择..</option>
                                <option value="0">是</option>
                                <option value="1">否</option>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">位置:</label>
                        <div class="layui-input-inline">
                            <select name="position">
                                <option value="" selected></option>
                                <?php foreach ($posArr as $k=>$v):?>
                                    <option value="<?php echo $k;?>"><?php echo $v;?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">设备:</label>
                        <div class="layui-input-inline">
                            <select name="device_type">
                                <option value="" selected>请选择..</option>
                                <?php foreach ($deviceArr as $device => $label): ?>
                                    <option value="<?php echo $device; ?>"><?php echo $label; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">下单时间:</label>
                        <div class="layui-input-inline">
                            <input name="cre_start_time"  id="cre_start_time" value="" class="layui-input date" placeholder="开始时间"/>
                        </div>
                        <label class="layui-form-label">~</label>
                        <div class="layui-input-inline">
                            <input name="cre_end_time" id="cre_end_time" value="" class="layui-input date" placeholder="结束时间"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">注册时间:</label>
                        <div class="layui-input-inline">
                            <input name="reg_start_time"  id="reg_start_time" class="layui-input date" placeholder="开始时间"/>
                        </div>

                        <label class="layui-form-label">~</label>
                        <div class="layui-input-inline">
                            <input name="reg_end_time" id="reg_end_time" class="layui-input date" placeholder="结束时间"/>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID:</label>
                        <div class="layui-input-inline">
                            <input name="user_id" class="layui-input" placeholder="用户ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">用户名:</label>
                        <div class="layui-input-inline">
                            <input name="username" class="layui-input" placeholder="用户名"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">订单编号:</label>
                        <div class="layui-input-inline">
                            <input name="order_sn" class="layui-input" placeholder="订单编号"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">渠道名称:</label>
                        <div class="layui-input-inline">
                            <input name="channel_name" class="layui-input" placeholder="渠道名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">&emsp;
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,laydate,$;
    layui.use(['layer', 'form', 'table', 'admin','laydate'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;
        laydate = layui.laydate;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:30
                ,limits:[10,30,50,100]
            }
            ,totalRow:true
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {type: 'checkbox'},
                {field: 'order_sn', title: '订单编号',align: 'center',width:200},
                {field: 'user_info', title:'用户信息', templet: function (row) {
                        var str='';
                        if(row.is_system==1){
                            str= "<p style='color: red'>"+row.user_id+"</p>"+"<p style='color: red'>"+row.nickname+"("+row.user_sex+")</p>"
                        }else {
                            str="<p >"+row.user_id+"</p>"+"<p>"+row.nickname+"("+row.user_sex+")</p>";
                        }
                        str+="<p>用户组:"+row.group_name+"</p>";
                        return str;
                    },width:150,align: 'center'},
                {field: 'head', title:'用户头像', width: 60, templet: function (row) {
                        if(row.head){
                            var link='<?php echo $mediaUrl;?>'+row.head;
                            return '<a target="_blank" href="'+link+'" ><img src="'+link+'" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="max-width: 50px;max-height: 50px"/></a>'
                        }
                        return '-';
                    },align: 'center'},
                {field: 'channel_name', title: '渠道',width:120,align: 'center'},
                {field: 'device_type', title: '设备',width:80,align: 'center'},
                {field: 'position', title: '位置',width:80,align: 'center'},
                {field: 'num', title: '套数',width:80,align: 'center'},
                {field: 'money', title: '金币',width:80,align: 'center'},
                {field: 'real_money', title: '实际金币',width:90,align: 'center'},
                {field: 'status_text', title: '状态',width:80,align: 'center'},
                {field: 'updated_at', title: '成功/失败时间',width:120,align: 'center', sort:true},
                {field: 'error_msg', title: '错误信息',style:'color:red',width:120,align: 'center'},
                {field: 'is_disabled', title: '是否显示',align: 'center',width: 100},
                {field: 'created_at', title: '创建时间',width:120,align: 'center', sort:true},
                {title:'操作'/*, toolbar: '#table-item-toolbar'*/,align: 'center', width:200,templet:function (row) {
                        var html = '<a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="detail">查看详情</a>';
                        if(row.status==0){
                            html += '<a class="layui-btn layui-btn-xs" lay-event="retry">重试</a>';
                        }
                        if(row.status==0||row.status==1){
                            html += '<a class="layui-btn layui-btn-xs layui-btn-warm" lay-event="refund">退款</a>';
                        }
                        html += '<a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</a>';

                        return html;
                    }}
            ]],
            done: function(res, curr, count) {
                $('.layui-table-tool-temp').html(
                    '<div style="color: red;">' + res['data']['summary_count'] + '</div>'+
                    '<div style="color: red;">' + res['data']['summary_money'] + '</div>'+
                    '<a class="layui-btn layui-btn-xs" lay-event="retry">重试</a>'+
                    '<button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>'
                );
            }
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function(obj){
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for(var index=0;index<data.length;index++)
            {
                ids.push(data[index]._id)
            }
            switch(obj.event) {
                case 'retry':
                    doRow(ids,'retry');
                    break;
                case 'refund':
                    doRow(ids,'refund');
                    break;
                case 'del':
                    doRow(ids,'del');
                    break;
            }
        });
        /*表格-行事件*/
        table.on('tool(table)', function(obj){
            var data = obj.data;
            switch (obj.event) {
                case 'detail':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/ai/detail'); ?>?_id="+data._id,
                        area:  ['1000px', '600px']
                    });
                    break;
                case 'retry':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids,'retry');
                    break;
                case 'refund':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids,'refund');
                    break;
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids,'del');
                    break;
            }
        });
        function doRow(ids,act) {
            if(ids==null || ids.length<1){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?",function() {
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/ai/do')?>",{act:act,id:ids.join(",")},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }
        /*表格排序事件*/
        table.on('sort(table)', function(obj){
            var order=obj.type==='asc'?1:-1;
            table.reload('table', {initSort: obj,where: {sort: obj.field,order: order }});
        });
        laydate.render({
            elem: '#cre_start_time'//指定元素
            , trigger: 'click'
            , type: 'datetime'
        });
        laydate.render({
            elem: '#cre_end_time'//指定元素
            , trigger: 'click'
            , type: 'datetime'
        });
        laydate.render({
            elem: '#reg_start_time'//指定元素
            , trigger: 'click'
            , type: 'datetime'
        });
        laydate.render({
            elem: '#reg_end_time'//指定元素
            , trigger: 'click'
            , type: 'datetime'
        });
    })
</script>
