<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">当前用户编号:</label>
                        <div class="layui-input-inline">
                            <input name="user_id1" class="layui-input"  autocomplete="off" placeholder="请输入名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">目标用户编号:</label>
                        <div class="layui-input-inline">
                            <input name="user_id2" class="layui-input"  autocomplete="off" placeholder="请输入名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                        <button  class="layui-btn layui-btn-sm layui-btn-danger" lay-submit="" lay-filter="doFindBtn">确认找回</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,$;
    layui.use(['layer', 'form', 'table', 'admin'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            // ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:30
                ,limits:[10,30,50,100]
            }
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {type: 'checkbox'}
                ,{field:'_id', title: 'ID',align: 'center'}
                ,{field:'username', title: '用户名',align: 'center'}
                ,{field:'nickname', title: '昵称',align: 'center'}
                ,{field:'device_id', title: '设备ID',align: 'center'}
                ,{field:'device_type', title: '设备类型',align: 'center'}
                ,{field:'group_name', title: '会员组',align: 'center'}
                ,{field:'group_start_time', title: 'VIP开始',align: 'center'}
                ,{field:'group_end_time', title: 'VIP结束',align: 'center'}
                ,{field:'last_at', title: '最后登陆',align: 'center'}
                ,{field:'register_at', title: '注册时间',align: 'center'}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        form.on('submit(doFindBtn)', function(obj){
            doFind();
            return false;
        });
        function doFind() {
            var user_id1=$("input[name='user_id1']").val();
            var user_id2=$("input[name='user_id2']").val();
            if(user_id1==''||user_id2==''){
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            layer.prompt({
                formType: 0,
                value: '',
                title: '请输入谷歌验证码',
                area: ['800px', '350px'] //
            }, function(value, index, elem){
                var loadIndex=layer.load(0,{time: 30*1000});
                doAjax("<?php echo createUrl('/user/doFind');?>",{user_id1:user_id1,user_id2:user_id2,google_code:value},function(res){
                    layer.close(loadIndex);
                    if(res.status=='y'){
                        layer.close(index);
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    }else{
                        showErrorMsg(res.error);
                    }
                });
            });
        }
    })
</script>
